language: php

sudo: required

services:
  - docker

env:
  - CIVICRM_UF=UnitTests
  - BUILD_ROOT=/opt/buildkit/build/test-build
  - EXTENSION_DIR=${BUILD_ROOT}/sites/all/modules/civicrm/tools/extensions

before_install:
  - docker pull mickadoo/civicrm:master
  - docker run -d --rm -v $PWD:${EXTENSION_DIR}/api4 --name=civicrm mickadoo/civicrm:master
  - docker ps -a
  - docker exec civicrm /bin/bash -c "cd ${BUILD_ROOT}; cv ext:enable api4"
  - docker exec civicrm /bin/bash -c "cd ${EXTENSION_DIR}/api4; phpunit4"

script:
  - phpunit4
